export const FETCH_REPOS_REQUEST = 'FETCH_REPOS_REQUEST';
export const FETCH_REPOS_SUCCESS = 'FETCH_REPOS_SUCCESS';
export const FETCH_REPOS_ERROR = 'FETCH_REPOS_ERROR';

export const SEARCH_TEXT_CHANGED = 'SEARCH_TEXT_CHANGED';
export const SEARCH_TEXT_DONE = 'SEARCH_TEXT_DONE';

export const FETCH_REPOSITORY_REQUEST = 'FETCH_REPOSITORY_REQUEST';
export const FETCH_REPOSITORY_SUCCESS = 'FETCH_REPOSITORY_SUCCESS';
export const FETCH_REPOSITORY_ERROR = 'FETCH_REPOSITORY_ERROR';

export const FETCH_REPOSITORY_README_REQUEST = 'FETCH_REPOSITORY_README_REQUEST';
export const FETCH_REPOSITORY_README_SUCCESS = 'FETCH_REPOSITORY_README_SUCCESS';
export const FETCH_REPOSITORY_README_ERROR = 'FETCH_REPOSITORY_README_ERROR';
